openapi: "3.0.0"
info:
  version: 1.0.0
  title: Bujo tracker
servers:
  - url: http://localhost:8080
paths:
  /health:
    get:
      summary: Healt check
      operationId: getHealthInfo
      responses:
        204:
          description: OK
        500:
          description: Service is down
  /users:
    post:
      summary: Register or update user
      operationId: createOrUpdateUser
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserIntent'
      responses:
        201:
          description: User created/updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserId'
        500:
          $ref: '#/components/responses/InternalError'
  /users/{telegram_id}:
    get:
      summary: Get user by telegram user id
      operationId: getTelegramUser
      parameters:
        - $ref: '#/components/parameters/TelegramUserPath'
      tags:
        - users
      responses:
        200:
          description: User created/updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          $ref: '#/components/responses/NotFoundResponse'
        500:
          $ref: '#/components/responses/InternalError'

  /tags:
    get:
      summary: Get all user tags
      operationId: getAllTags
      parameters:
        - $ref: '#/components/parameters/UserHeader'
      tags:
        - tags
      responses:
        200:
          description: List of tags
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagList'
        500:
          $ref: '#/components/responses/InternalError'
  /tags/{id}:
    post:
      summary: Update the tag
      operationId: updateTag
      parameters:
        - $ref: '#/components/parameters/UserHeader'
        - $ref: '#/components/parameters/IdPath'
      tags:
        - tags
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagIntent'
      responses:
        200:
          description: Updated tag
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        500:
          $ref: '#/components/responses/InternalError'

  /habits:
    parameters:
      - $ref: '#/components/parameters/UserHeader'
    post:
      summary: Create habit
      operationId: createHabit
      tags:
        - habits
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HabitIntent'
      responses:
        201:
          description: Habit created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Habit'
        500:
          $ref: '#/components/responses/InternalError'
    get:
      summary: Get all habits
      operationId: getAllHabits
      responses:
        200:
          description: User habits
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HabitList'
        500:
          $ref: '#/components/responses/InternalError'
  /habits/{id}:
    parameters:
      - $ref: '#/components/parameters/UserHeader'
      - $ref: '#/components/parameters/IdPath'
    get:
      summary: Get user habit
      operationId: getHabit
      responses:
        200:
          description: Habit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Habit'
        404:
          $ref: '#/components/responses/NotFoundResponse'
        500:
          $ref: '#/components/responses/InternalError'
    post:
      summary: Update habit
      operationId: updateHabit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Habit'
      responses:
        200:
          description: Updated habit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Habit'
        404:
          $ref: '#/components/responses/NotFoundResponse'
        500:
          $ref: '#/components/responses/InternalError'
    delete:
      summary: Delete habit
      operationId: deleteHabit
      responses:
        200:
          description: Deleted habit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Habit'
        404:
          $ref: '#/components/responses/NotFoundResponse'
        500:
          $ref: '#/components/responses/InternalError'

components:
  parameters:
    TelegramUserPath:
      in: path
      name: telegram_id
      schema:
        type: number
    IdPath:
      in: path
      name: id
      schema:
        $ref: '#/components/schemas/UUID'
    UserHeader:
      in: header
      name: X-Auth-Id
      description: User uuid
      schema:
        $ref: '#/components/schemas/UUID'
      required: true

  responses:
    NotFoundResponse:
      description: Object not found
      content:
        application/json:
          schema:
            type: string
            example: "Error: Not Found"
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            example: "Error: Internal Error"

  schemas:
    UUID:
      type: string
      format: uuid
    Id:
      type: object
      required:
        - value
      properties:
        value:
          $ref: '#/components/schemas/UUID'
    TagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
      default: []
    UserId:
      $ref: '#/components/schemas/Id'
    UserIntent:
      type: object
      required:
        - telegramId
        - firstName
        - lastName
        - language
      properties:
        telegramId:
          description: Long id of Telegram user
          type: number
        firstName:
          description: First name
          type: string
        lastName:
          description: Last name
          type: string
        language:
          description: language code for translations
          type: string
    User:
      type: object
      required:
        - id
        - telegramId
        - firstName
        - lastName
        - language
      properties:
        id:
          $ref: '#/components/schemas/UserId'
        telegramId:
          description: Long id of Telegram user
          type: number
        firstName:
          description: First name
          type: string
        lastName:
          description: First name
          type: string
        language:
          description: language code for translations
          type: string
    TagIntent:
      type: object
      required:
        - name
      properties:
        name:
          description: Tag name
          type: string
    Tag:
      type: object
      required:
        - id
        - name
      properties:
        id:
          $ref: '#/components/schemas/TagId'
        name:
          description: Tag name
          type: string
    TagOrIntent:
      type: object
      oneOf:
        - $ref: '#/components/schemas/Tag'
        - $ref: '#/components/schemas/TagIntent'
    TagOrIntentList:
      type: array
      items:
        $ref: '#/components/schemas/TagOrIntent'
      default: []
    Period:
      enum:
        - Day
        - Week
    DateTime:
      type: string
      format: 'date-time'
    HabitIntent:
      type: object
      required:
        - name
        - tags
        - numberOfRepetitions
        - period
        - values
      properties:
        name:
          type: string
        tags:
          $ref: '#/components/schemas/TagOrIntentList'
        numberOfRepetitions:
          type: integer
        period:
          $ref: '#/components/schemas/Period'
        quote:
          type: string
        bad:
          type: boolean
          description: Is it bad habit
          default: false
        startFrom:
          $ref: '#/components/schemas/DateTime'
        values:
          $ref: '#/components/schemas/ValueTemplateList'
    HabitList:
      type: array
      items:
        - $ref: '#/components/schemas/Habit'
      default: []
    Habit:
      type: object
      required:
        - id
        - name
        - tags
        - numberOfRepetitions
        - period
        - values
      properties:
        id:
          $ref: '#/components/schemas/HabitId'
        name:
          type: string
        tags:
          $ref: '#/components/schemas/TagOrIntentList'
        numberOfRepetitions:
          type: integer
        period:
          $ref: '#/components/schemas/Period'
        quote:
          type: string
        bad:
          type: boolean
          description: Is it bad habit
          default: false
        startFrom:
          $ref: '#/components/schemas/DateTime'
        values:
          $ref: '#/components/schemas/ValueTemplateList'
    ValueTemplateList:
      type: array
      items:
        $ref: '#/components/schemas/ValueTemplate'
      default: []
    ValueTemplate:
      type: object
      required:
        - type
        - values
      properties:
        type:
          $ref: '#/components/schemas/ValueType'
        values:
          $ref: '#/components/schemas/Values'
        name:
          type: string
          description: Name of template value
    Values:
      type: array
      items:
        - type: string
      default: []
    ValueType:
      enum:
        - Mood
        - EndDate
    ValueTemplateId:
      $ref: '#/components/schemas/Id'
    ValueId:
      $ref: '#/components/schemas/Id'
    ActionId:
      $ref: '#/components/schemas/Id'
    TagId:
      $ref: '#/components/schemas/Id'
    HabitId:
      $ref: '#/components/schemas/Id'
