openapi: "3.0.0"
info:
  version: 1.0.0
  title: Bujo tracker
paths:
  /users:
    post:
      summary: Register user
      operationId: addUser
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        200:
          description: User created/updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackerUserResponse'

# =========================================================================
components:
  schemas:
    UUID:
      type: string
      format: uuid

    CreateUserRequest:
      type: object
      required:
        - telegramId
        - firstName
        - lastName
        - language
      properties:
        telegramId:
          description: Long id of Telegram user
          type: number
        firstName:
          type: string
        lastName:
          type: string
        language:
          description: language code for translations
          type: string

    TrackerUserResponse:
      type: object
      required:
        - id
        - telegramId
        - firstName
        - lastName
        - language
      properties:
        id:
          $ref: '#/components/schemas/UserId'
        telegramId:
          description: Long id of Telegram user
          type: number
        firstName:
          type: string
        lastName:
          type: string
        language:
          description: language code for translations
          type: string

    Id:
      type: object
      required:
        - value
      properties:
        value:
          $ref: '#/components/schemas/UUID'
    ValueTemplateId:
      $ref: '#/components/schemas/Id'
    ValueId:
      $ref: '#/components/schemas/Id'
    ActionId:
      $ref: '#/components/schemas/Id'
    TagId:
      $ref: '#/components/schemas/Id'
    UserId:
      $ref: '#/components/schemas/Id'
    HabitId:
      $ref: '#/components/schemas/Id'
