version: '3'
services:
  postgres:
    image: postgres
    build:
      context: postgres
    ports:
      - "5432:5432"
    command:
      - "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3