apiVersion: v1
kind: ConfigMap
metadata:
  name: bujo-tracker-config
  namespace: bujo-prod
  labels:
    app: bujo_tracker
data:
  DB_URL: "jdbc:postgresql://postgres.db/bujo"
  DB_DRIVER: "org.postgresql.Driver"
  DB_USER: "bujo_user"
  DB_MAX_POOL: "10"
  APP_PORT: "8080"
  SWAGGER_PORT: "8085"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bujo-tracker
  namespace: bujo-prod
  labels:
    app: bujo_tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bujo_tracker
  template:
    metadata:
      labels:
        app: bujo_tracker
    spec:
      nodeSelector:
        host: self
      containers:
        - name: bujo-tracker
          image: j0rsa/bujo-tracker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: bujo-tracker-config
            - secretRef:
                name: bujo-tracker-secrets
          ports:
            - containerPort: 8080
            - containerPort: 8085
