apiVersion: v1
kind: ConfigMap
metadata:
  name: bujo-tracker-config
  namespace: bujo-prod
  labels:
    app: bujo_tracker
data:
  DB_URL: "jdbc:postgresql://postgres.db.svc.cluster.local:5432/bujo_user"
  DB_DRIVER: "org.postgresql.Driver"
  DB_USER: "bujo_user"
  DB_MAX_POOL: "10"
  APP_PORT: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bujo-tracker
  namespace: bujo-prod
  labels:
    app: bujo_tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bujo_tracker
  template:
    metadata:
      labels:
        app: bujo_tracker
    spec:
      containers:
        - name: bujo-tracker
          image: docker.pkg.github.com/j0rsa/bujo-tracker/tracker:d645fb4
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: bujo-tracker-config
            - secretRef:
                name: bujo-tracker-secrets
